<?php defined('SYSTEMPATH') || exit('No direct script access allowed'); ?>

CRITICAL - 2019-12-03 06:04:58 --> Class 'App\Controllers\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:05:02 --> Class 'App\Controllers\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:05:43 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:06:14 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:06:15 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:06:39 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:07:10 --> Class 'App\Models\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:07:10 --> Class 'App\Models\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:07:10 --> Class 'App\Models\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:07:13 --> Class 'App\Models\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:07:14 --> Class 'App\Models\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:07:14 --> Class 'App\Models\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:07:28 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:30:38 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:30:38 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:31:51 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:31:52 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:31:52 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:31:52 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:34:02 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:34:20 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(116): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:38:58 --> Class '\CodeIgniter\Database\postgre\Connection' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(328): CodeIgniter\Database\Config::connect('default')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): CodeIgniter\Model->__construct()
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 06:39:49 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:39:50 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:40:29 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:40:30 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:40:30 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:41:15 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:41:15 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:41:15 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:42:11 --> Class 'BaseModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(365): require_once()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/opt/lampp/htdo...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\User...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\User...')
#4 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): spl_autoload_call('App\\Models\\User...')
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#6 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2019-12-03 06:42:12 --> Class 'BaseModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(365): require_once()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/opt/lampp/htdo...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\User...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\User...')
#4 /opt/lampp/htdocs/firstproject/app/Controllers/User.php(8): spl_autoload_call('App\\Models\\User...')
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#6 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2019-12-03 06:45:27 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:45:51 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:45:51 --> Class 'App\Controllers\DepartmentModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:48:04 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:48:27 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:49:12 --> Class 'App\Models\App\Models\BaseModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(365): require_once()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/opt/lampp/htdo...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Depa...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Depa...')
#4 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(9): spl_autoload_call('App\\Models\\Depa...')
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#6 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2019-12-03 06:49:12 --> Class 'App\Models\App\Models\BaseModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(365): require_once()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/opt/lampp/htdo...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Depa...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Depa...')
#4 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(9): spl_autoload_call('App\\Models\\Depa...')
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#6 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2019-12-03 06:49:46 --> Class 'App\Controllers\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:49:49 --> Class 'App\Controllers\UserModel' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\User->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 06:57:47 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:57:48 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:57:48 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:59:01 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:59:02 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 06:59:02 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:00:42 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:00:43 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:00:43 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:00:43 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:00:43 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:00:43 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:01:01 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(437): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->findAll()
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:01:09 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:01:09 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:01:09 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:09:50 --> dir(aa): failed to open dir: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dir(aa): failed...', '/opt/lampp/htdo...', 372, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(372): dir('aa')
#2 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2019-12-03 07:11:37 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:13:42 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:16:51 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:16:57 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:16:58 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:17:43 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:18:37 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(645): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:18:37 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(645): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:18:37 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(645): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:18:59 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:20:31 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:21:14 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:22:20 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:22:21 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:22:21 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:22:21 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:22:22 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/opt/lampp/htdo...', 98, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(98): pg_connect('host=192.168.64...')
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1783): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/Model.php(373): CodeIgniter\Database\BaseBuilder->get()
#6 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(11): CodeIgniter\Model->find(1)
#7 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#8 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#9 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2019-12-03 07:23:11 --> Call to undefined function App\Controllers\pprint_r()
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 20:10:37 --> Use of undefined constant APP_PATH - assumed 'APP_PATH' (this will throw an Error in a future version of PHP)
#0 /opt/lampp/htdocs/firstproject/app/Controllers/Department.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', '/opt/lampp/htdo...', 10, Array)
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(847): App\Controllers\Department->index()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(338): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Department))
#3 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2019-12-03 23:45:38 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:47:10 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:47:10 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:50:40 --> Class 'App\Controllers\App\Library\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:54:57 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:54:58 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:54:58 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:58:44 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:58:44 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2019-12-03 23:58:45 --> Class 'App\Controllers\App\Libraries\View' not found
#0 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(823): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->createController()
#2 /opt/lampp/htdocs/firstproject/vendor/codeigniter4/framework/system/CodeIgniter.php(246): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/firstproject/public/index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
